name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
  runs-on: ubuntu-latest
  steps:
    - name: Printing Greetings
      echo "Hello World!"
    - name: print goodbye
      echo "Done - bye!"
  
